### PR TITLE
Ported the removed DefaultMessageNormalizer to the BernardBundle

### LINKED ISSUE #51: 2.0.1 not compatible with 2.0.0
Using `DefaultMessage` you now get the following error:

```
UnexpectedValueException: No supported normalizer found for "Bernard\Message\DefaultMessage".

/workspace/vendor/bernard/normalt/src/Normalizer/AggregateNormalizer.php:43
/workspace/vendor/bernard/bernard/src/Normalizer/EnvelopeNormalizer.php:36
/workspace/vendor/bernard/normalt/src/Normalizer/AggregateNormalizer.php:40
/workspace/vendor/bernard/bernard/src/Serializer.php:41
/workspace/vendor/bernard/bernard/src/Queue/PersistentQueue.php:98
/workspace/vendor/bernard/bernard/src/Consumer.php:81
```

Is tihs a bug or am i missing an upgrade guide?

### PR DESCRIPTION
**Pull request by acrobat**
Added a bc layer for the removed `DefaultMessageNormalizer` from the bernard lib.

fixes #51 

/cc @sagikazarmark

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Shouldn't it extend the PlainMessageNormalizer from the bernard package?

**Comment by acrobat** [comment]
I didn't do that because each method would be different, but maybe that's a good idea. Will update the PR!

**Comment by acrobat** [comment]
@sagikazarmark anymore changes needed here? Otherwise I merge this PR and tag a new patch release

File: Normalizer/DefaultMessageNormalizer.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+        return new DefaultMessage($data['name'], $data['arguments']);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function supportsDenormalization($data, $type, $format = null)
+    {
+        return $type === 'Bernard\Message\DefaultMessage';
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Thinking if this should accept a PlainMessage as well.

File: Normalizer/DefaultMessageNormalizer.php [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function supportsNormalization($data, $format = null)
+    {
+        return $data instanceof DefaultMessage;
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Same here

File: Normalizer/DefaultMessageNormalizer.php [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+use Bernard\Normalizer\PlainMessageNormalizer;
+
+class DefaultMessageNormalizer extends PlainMessageNormalizer
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function normalize($object, $format = null, array $context = [])
+    {
+        @trigger_error('The '.__NAMESPACE__.'\DefaultMessageNormalizer class is deprecated and will removed in version 3.0. Use '.__NAMESPACE__.'\PlainMessageNormalizer instead.', E_USER_DEPRECATED);
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: You sure `__NAMESPACE__` is correct here before PlainMessageNormalizer? I would rather use `PlainMessageNormalizer::class`

File: Normalizer/DefaultMessageNormalizer.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+
+        parent::normalize($object, $format, $context);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function denormalize($data, $class, $format = null, array $context = [])
+    {
+        @trigger_error('The '.__NAMESPACE__.'\DefaultMessageNormalizer class is deprecated and will removed in version 3.0. Use '.__NAMESPACE__.'\PlainMessageNormalizer instead.', E_USER_DEPRECATED);
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Same here

File: Normalizer/DefaultMessageNormalizer.php (hunk 3 above)
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Also, you could use `__CLASS__` instead of DefaultMessageNormalizer

File: Normalizer/DefaultMessageNormalizer.php (hunk 1 above)
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Also, you can use class constant here as well.

**Comment by sagikazarmark** [comment]
Just a few minor things.

File: Normalizer/DefaultMessageNormalizer.php (hunk 1 above)
Comment (acrobat) [inline Normalizer/DefaultMessageNormalizer.php]: The namespace was indeed wrong. Fixed!

**Comment by acrobat** [comment]
Fixed the comments!

File: Normalizer/DefaultMessageNormalizer.php [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+use Bernard\Normalizer\PlainMessageNormalizer;
+
+class DefaultMessageNormalizer extends PlainMessageNormalizer
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function normalize($object, $format = null, array $context = [])
+    {
+        @trigger_error('The '.__NAMESPACE__.'\\'.__CLASS__.' class is deprecated and will removed in version 3.0. Use '.PlainMessageNormalizer::class.' instead.', E_USER_DEPRECATED);
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: I believe `__CLASS__` already returns FQCN.

File: Normalizer/DefaultMessageNormalizer.php [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+
+        return new DefaultMessage($data['name'], $data['arguments']);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function supportsDenormalization($data, $type, $format = null)
+    {
+        return $type === DefaultMessage::class;
```
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Comment about plain message here got lost somehow. Shouldn't we?

File: Normalizer/DefaultMessageNormalizer.php (hunk 5 above)
Comment (sagikazarmark) [inline Normalizer/DefaultMessageNormalizer.php]: Proof: https://3v4l.org/54Isq

Comment (acrobat) [inline Normalizer/DefaultMessageNormalizer.php]: my bad, fixed!

File: Normalizer/DefaultMessageNormalizer.php (hunk 6 above)
Comment (acrobat) [inline Normalizer/DefaultMessageNormalizer.php]: Should we mix the supported classes/normalizers? The plainmessage normalizer is also registered in the service config https://github.com/bernardphp/BernardBundle/blob/master/Resources/config/services.xml#L68

**Comment by acrobat** [comment]
@sagikazarmark most of the comments are addressed. What do you think, ready for merge?
